### ISSUE TITLE
User is always being redirected to / if logged in regardless of the path typed in the url

### ISSUE THREAD

**Issue by cherylli** [chingu-voyages/v40-bears-team-37#70]
**Describe the problem**
User is always being redirected to / if logged in regardless of the path typed in the url. 

For example, if user typed localhost/settings in the address bar, it will always be redirected to /, so user can never navigate to the settings pages unless using the sidebar (navbar)

path switching from navbar is fine.

**Actual behavior**
A clear and concise description of what you experienced.

**Expected behavior**

**To Reproduce**

**Screenshots**
If applicable, add screenshots or gifs to help explain your problem.

**Your Environment:**
 - Your browser & its version
 - Any other software that may impact this issue

**Additional Information**

**Comment by amirfakhrullah** [comment]
I think this bug comes from the public routes. We're lacking some loaders component to render during fetching the auth check api.

## Situation

If logged in, when going to `/settings` page, the first thing the app do is calling `api/auth/check`, and before the data returns (api request can take a while), `user` will still be null and `isAuthed` will still be false, so based on that the app will render the `PublicRoutes`, and then right after the data from `api/auth/check` is returned, the `PublicRoutes` will redirect to `/` due to this conditional checking in `PublicRoutes`: 

```ts
if (auth.isAuthed) {
    return <Navigate to="/" state={{ from: location }} replace />;
}
```

## Solution
during the fetching of `api/auth/check` we should make the app to not render either of `PublicRoutes` or `PrivateRoutes`, instead it should render a separate component (loader).

So in `App.tsx`, maybe we can put it something like this:

```ts
function App() {
  const { isLoading } = useAuth(); // isLoading => loading state for api/auth/check

 if (isLoading) return <Loader />;  // we should have a loader component

  return (
    <Routes>
      <Route
        path="/"
        element={
          <PrivateRoute>
            <CalendarPage />
          </PrivateRoute>
        }
      />
      <Route
        path="/search"
        element={
          <PrivateRoute>
            <Search />
          </PrivateRoute>
        }
      />
      <Route
        path="/settings"
        element={
          <PrivateRoute>
            <Settings />
          </PrivateRoute>
        }
      />
      <Route
        path="/login"
        element={
          <PublicRoute>
            <Login />
          </PublicRoute>
        }
      />
      <Route
        path="/signup"
        element={
          <PublicRoute>
            <Signup />
          </PublicRoute>
        }
      />
    </Routes>
  );
}
```

In the AuthContext, we should have a loading state for `api/auth/check`
